[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
validator = { workspace = true }
oas3-gen-support = { workspace = true }
reqwest = { version = "0.13.2", features = ["json"] }
anyhow = { workspace = true }
http = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
iroh = "0.96.1"
iroh-tickets = "0.3.0"
derive_more = { version = "2.1.1", features = ["from"] }
