services:
  server1:
    environment:
      RUST_LOG: trace
  server2:
    environment:
      RUST_LOG: trace
  server3:
    environment:
      RUST_LOG: trace
  server4:
    environment:
      RUST_LOG: trace
  server5:
    environment:
      RUST_LOG: trace
