[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
axum = "0.8.8"
http = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
validator = { workspace = true }
oas3-gen-support = { workspace = true }
