[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
http = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
validator = { workspace = true }
oas3-gen-support = { workspace = true }
hyparview = "0.1.3"
plumtree = "0.1.1"
rand = "0.6.5"
uuid = { workspace = true }
smart-default = "0.7.1"
derive_more = { workspace = true }
tokio-util = { workspace = true }
futures-core = "0.3.32"
futures-util = { workspace = true }
serde_json.workspace = true
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tower-http = { workspace = true }
