[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
axum = "0.8.8"
http = "1.0.0"
chrono = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
validator = { version = "0.20", features = ["derive"] }
oas3-gen-support = "0.25"
